config/routes.rb
Rails.application.routes.draw do
  get 'showtimes/index'

  get 'showtimes/new'

  get 'orders/index'

  get 'orders/new'

  root "movies#index"

  resources :movies, only: [:index, :show] do
    resources :showtimes
    resources :orders, only: [:new, :create]
  end
  resources :showtimes

  namespace :admin do
    resources :orders,    only: [:index]
    resources :movies,    only: [:index, :new, :create, :destroy]
    resources :theatres,  only: [:index, :new, :create, :edit, :update, :destroy]
    resource  :dashboard, only: [:show], controller: :dashboard
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    def show

    end
  end
end

app/views/admin/dashboard/show.html.haml
%h4.title Admin Actions
.divider
.section.center-align
  = link_to admin_orders_path, class: 'waves-effect waves-light btn-large green darken-3' do
    %i.material-icons.left credit_card
    Orders
  %br
  %br
  =link_to admin_theatres_path, class: 'waves-effect waves-light btn-large pink' do
    %i.material-icons.left local_movies
    Theatres
  %br
  %br
  = link_to admin_movies_path, class: 'waves-effect waves-light btn-large' do
    %i.material-icons.left movies
    Movies
  %br
  %br
  =link_to new_admin_movie_path, class: 'waves-effect waves-light btn-large teal accent-4' do
    %i.material-icons.left movie_filter
    New Movie
  %br
  %br
  =link_to showtimes_path, class: 'waves-effect waves-light btn-large indigo' do
    %i.material-icons.left access_time
    Showtimes
  %br
  %br
  =link_to new_showtime_path, class: 'waves-effect waves-light btn-large blue' do
    %i.material-icons.left alarm_add
    New Showtime