config/routes.rb
Rails.application.routes.draw do
  get 'showtimes/index'

  get 'showtimes/new'

  get 'orders/index'

  get 'orders/new'

  root "movies#index"

  resources :movies, only: [:index, :show] do
    resources :showtimes
    resources :orders, only: [:new, :create]
  end
  resources :showtimes

  namespace :admin do
    resources :orders,    only: [:index]
    resources :movies,    only: [:index, :new, :create, :destroy]
    resources :theatres,  only: [:index, :new, :create, :edit, :update, :destroy]
    resource  :dashboard, only: [:show], controller: :dashboard
  end
end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
  has_many :showtimes, dependent: :destroy, inverse_of: :theatre
  has_many :orders, inverse_of: :theatre

  validates :number, uniqueness: true,
                     presence:   true,
                     numericality: { greater_than: 0 }

  validates :capacity, presence: true,
                       numericality: { greater_than: 0 }

  def display_name
    "Theatre: #{number} - capacity: #{capacity}"
  end
end

app/controllers/admin/theatres_controller.rb
module Admin
  class TheatresController < ApplicationController
    def index
      @theatres = Theatre.all
    end

    def new
      @theatre = Theatre.new
    end

    def create
      @theatre = Theatre.new(theatre_params)

      respond_to do |format|
        if @theatre.save
          format.html { redirect_to admin_theatres_path, notice: 'Theatre was created successfully' }
          format.js
        else
          format.html { render 'new' }
          format.js
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @theatre.save
          format.html { redirect_to admin_theatres_path, notice: 'Theatre was updated successfully' }
          format.js
        else
          format.html { render 'edit' }
          format.js
        end
      end
    end

    def destroy
      @theatre.destroy

      flash[:notice] = "Theatre has been deleted"
      redirect_to admin_theatres_path
    end

    protected

    def theatre_params
      params.require(:theatre).permit(:capacity, :number)
    end
  end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def show
  end
end

app/views/admin/theatres/_form.html.haml
= simple_form_for([:admin,@theatre]) do |f|
  = f.input :capacity
  = f.input :number
  = f.button :submit

app/views/admin/theatres/edit.html.haml
= render 'form'

app/views/admin/theatres/index.html.haml
%br
%h4.title Theatres
= link_to 'New Theatre', new_admin_theatre_path, class: 'waves-effect waves-light btn right'

.row
%table.striped
  %thead
    %tr
      %th Theatre #
      %th Total Capacity
  %tbody
    #theatres
    - @theatres.each do |theatre|
      %tr
        %td= theatre.number
        %td= theatre.capacity

app/views/admin/theatres/new.html.haml
%br
%h4.title New Theatre
= render 'form'