config/routes.rb
Rails.application.routes.draw do
  get 'showtimes/index'

  get 'showtimes/new'

  get 'orders/index'

  get 'orders/new'

  root "movies#index"

  resources :movies, only: [:index, :show] do
    resources :showtimes
    resources :orders, only: [:new, :create]
  end
  resources :showtimes

  namespace :admin do
    resources :orders,    only: [:index]
    resources :movies,    only: [:index, :new, :create, :destroy]
    resources :theatres,  only: [:index, :new, :create, :edit, :update, :destroy]
    resource  :dashboard, only: [:show], controller: :dashboard
  end
end

app/views/layouts/_navigation.html.haml
.navbar-fixed
  %nav
    .nav-wrapper
      = link_to root_path do
        =image_tag asset_path('logo.png'), :size => '295x47', class: 'logo-img brand-logo'
      %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        %li
          = link_to 'Admin', admin_dashboard_path
      %ul.side-nav#mobile-demo
        %li
          = link_to 'Admin', admin_dashboard_path

app/views/layouts/_notifications.html.haml
- if flash.any?
  - flash.each do |key, message|
    :coffeescript
      `Materialize.toast("#{message}", 5000, "toast-#{key}")`

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}
    %title
      - if content_for?(:title)
        = yield(:title)
      - else
        LaunchPadango
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width", :name => "viewport"}/
  %body
    = render 'layouts/notifications'
    = render 'layouts/navigation'
    .container
      .row
        = yield